### ISSUE TITLE
Allow numpy ndarrays to work with JSON

### ISSUE THREAD

**Issue by mspraggs** [ShaneDrury/pyon#21]
I've just tried doing a measurement where the measurement returns a dict with one of the values containing a numpy ndarray. Unfortunately it doesn't look like the JSON format can handle these in their raw form (I get the error "XXXX is not JSON serializable"). Perhaps we could have some sort of handler to deal with this automatically?

**Comment by ShaneDrury** [comment]
That's odd, I thought Project._sanitize_dic() was supposed to stop these kinds of errors.
It should be basically doing the equivalent of:

``` python
import numpy
import simplejson
x = np.array([1, 2, 3])
simplejson.dumps(x)  # TypeError
simplejson.dumps(str(x))  # '"[1 2 3]"'
```

**Comment by mspraggs** [comment]
It seems that the array that raised this error was an array of NaNs, if
that helps.

Matt

**Comment by mspraggs** [comment]
A traceback:

``````
Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/home/matthew/Downloads/pyon/pyon/core/management/__init__.py", line 126, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.6.5-py2.7.egg/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.6.5-py2.7.egg/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.6.5-py2.7.egg/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/matthew/Downloads/pyon/pyon/core/management/commands/run.py", line 10, in handle
    project.main()
  File "/home/matthew/Downloads/pyon/pyon/core/project.py", line 67, in main
    self._generic_main(self.measurements, "measurement", "meas")
  File "/home/matthew/Downloads/pyon/pyon/core/project.py", line 58, in _generic_main
    self.dump_result(object_name, obj_results)
  File "/home/matthew/Downloads/pyon/pyon/core/project.py", line 130, in dump_result
    simplejson.dump(to_dump, f, namedtuple_as_object=True)
  File "/usr/local/lib/python2.7/dist-packages/simplejson-3.5.2-py2.7-linux-x86_64.egg/simplejson/__init__.py", line 267, in dump
    for chunk in iterable:
  File "/usr/local/lib/python2.7/dist-packages/simplejson-3.5.2-py2.7-linux-x86_64.egg/simplejson/encoder.py", line 632, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/local/lib/python2.7/dist-packages/simplejson-3.5.2-py2.7-linux-x86_64.egg/simplejson/encoder.py", line 591, in _iterencode_dict
    for chunk in chunks:
  File "/usr/local/lib/python2.7/dist-packages/simplejson-3.5.2-py2.7-linux-x86_64.egg/simplejson/encoder.py", line 481, in _iterencode_list
    for chunk in chunks:
  File "/usr/local/lib/python2.7/dist-packages/simplejson-3.5.2-py2.7-linux-x86_64.egg/simplejson/encoder.py", line 642, in _iterencode
    o = _default(o)
  File "/usr/local/lib/python2.7/dist-packages/simplejson-3.5.2-py2.7-linux-x86_64.egg/simplejson/encoder.py", line 246, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: array([ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan]) is not JSON serializable```
``````
